config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true, length: { minimum: 6, maximum: 100 }
	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles, dependent: :destroy
	before_save { self.email = email.downcase }
	validates :username, presence: true, uniqueness: { case_sensitive: false },
							length: { minimum: 3, maximum: 25 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i # Regex for email validation
	validates :email, presence: true, uniqueness: { case_sensitive: false },
							length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
	@article.user = User.first
    if @article.save
			flash[:notice] = "Article was successfully created!"
      redirect_to @article
    else
      render 'new', status: 422
    end
  end

	def edit
	end

	def update

		if @article.update(article_params)
			flash[:notice] = "Article was successfully updated!"
			redirect_to @article
		else
			render 'edit', status: 422
		end
	end

	def destroy
		@article.destroy

		flash[:notice] = "Article was successfully deleted!"
		redirect_to articles_path
	end

	private 
	
	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	# This is the home page
	def home
	end
	
	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
	<h2>The following errors prevented the article from being saved:</h2>
	<% @article.errors.full_messages.each do |msg| %>
		<p><%= msg %></p>
	<% end %>	
<% end %>

<%= form_with(model: @article, local: true) do |form| %>
	<p>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
	</p>
 
	<p>
		<%= form.label :description %><br>
		<%= form.text_area :description %>
	</p>
 
	<p>
		<%= form.submit %>
	</p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article: <%= @article.title %></h1>

<%= render 'form' %>

<%= link_to 'Return to all articles', articles_path %>

app/views/articles/index.html.erb
<h1 class="text-2xl text-slate-900">Showing All Article details</h1>
<p class="text-sky-500"><%= link_to 'Add new Article', new_article_path %></p>
<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
<table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
  <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
    <tr>
        <th scope="col" class="px-6 py-3">Title</th>
        <th scope="col" class="px-6 py-3">Description</th>
		<th colspan="3" scope="col" class="px-6 py-3">Actions</th>
    </tr>
  </thead>
	<tbody>
		<% @articles.each do |article| %>
			<tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
				<td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"><%= article.title %></td>
				<td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"><%= article.description %></td>
				<td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"><%= link_to 'View', article_path(article) %></td>
				<td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"><%= link_to 'Edit', edit_article_path(article) %></td>
				<td scope="row" class="px-6 py-4 font-medium text-red-900 whitespace-nowrap dark:text-white"><%= link_to 'Delete', article_path(article), data: { "turbo_method": :delete, class: "text-red-500" } %></td>
			</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/articles/new.html.erb
<h1>Create a new Article</h1>

<%= render 'form' %>

<%= link_to 'Return to all articles', articles_path %>

app/views/articles/show.html.erb
<h1>Showing Article details</h1>
<p><%= @article.title %></p>
<p><%= @article.description %></p>
<%= link_to 'All Articles', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
	<div class="font-bold alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="flex flex-wrap items-center justify-between max-w-screen-xl p-4 mx-auto">
  <a href="<%= root_path %>" class="flex items-center">
      <img src="https://flowbite.com/docs/images/logo.svg" class="h-8 mr-3" alt="Flowbite Logo" />
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Scribe</span>
  </a>
  <div class="flex md:order-2">
    <button type="button" data-collapse-toggle="navbar-search" aria-controls="navbar-search" aria-expanded="false" class="md:hidden text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5 mr-1" >
      <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
      <span class="sr-only">Search</span>
    </button>
    <div class="relative hidden md:block">
      <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
        <svg class="w-5 h-5 text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
        <span class="sr-only">Search icon</span>
      </div>
      <input type="text" id="search-navbar" class="block w-full p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search...">
    </div>
    <button data-collapse-toggle="navbar-search" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-search" aria-expanded="false">
      <span class="sr-only">Open menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
    </button>
  </div>
    <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-search">
      <div class="relative mt-3 md:hidden">
        <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
          <svg class="w-5 h-5 text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
        </div>
        <input type="text" id="search-navbar" class="block w-full p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search...">
      </div>
      <ul class="flex flex-col p-4 mt-4 font-medium border border-gray-100 rounded-lg md:p-0 bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <a href="<%= root_path %>" class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500" aria-current="page">Home</a>
        </li>
        <li>
          <a href="<%= about_path %>" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
        </li>
        <li>
          <a href="<%= articles_path %>" class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Articles</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="max-w-screen-xl py-5 mx-auto">
      <%= render "layouts/messages" %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/home.html.erb
<h1>Homepage</h1>